name: Generate ASCII

on: 
   push

jobs:
  ascii_jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay cmd
      run: cowsay -f dragon "Run RUN" >> dragon.txt

    - name: Read file
      run: cat dragon.txt

    - name: List repo files
      run: ls -ltra



