name: Generate ASCII

on: 
   push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Execute shell script
      run: |
        touch dragon.txt
        echo "test" > dragon.txt
    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: dragon text file
        path: dragon.txt

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
    - name: Download file
      uses: actions/download-artifact@v3
      with:
        name: dragon text file
    - name: list
      run: ls -ltra

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:
    - name: list files
      run: ls -al

# jobs:
#   ascii_jobs:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repo
#       uses: actions/checkout@v4
#     - name: Execute shell script
#       run: |
#         chmod +x ascii-script.sh
#         ./ascii-script.sh
    
    # - name: Install cowsay program
    #   run: sudo apt-get install cowsay -y

    # - name: Execute cowsay cmd
    #   run: cowsay -f dragon "Run RUN" >> dragon.txt

    # - name: Read file
    #   run: cat dragon.txt

    # - name: List repo files
    #   run: ls -ltra



